---
# tasks file for roles/nginx

- name: NGINX | Install Web Server
  block:
    - name: On RedHat Family
      ansible.builtin.yum:
        name: nginx
      when:
        ansible_pkg_mgr == "yum"
    - name: On Debian Family
      ansible.builtin.apt:
        name: nginx
      when:
        ansible_pkg_mgr == "apt"


- name: NGINX | Create global config
  become: true
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: NGINX | Restarted service
